# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-03-22T16:16:25Z"
  labels:
    app: my-pod
  name: my-pod
spec:
  containers:
  - args:
    - mariadbd
    image: docker.io/library/mariadb:latest
    name: wptest-db
    ports:
    - containerPort: 80
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: d88b83ee2a406925b6fd5efb630953d14c1cf0c11be69b9802fe0ed2d9cc3565-pvc
  - args:
    - apache2-foreground
    image: docker.io/library/wordpress:latest
    name: wptest-web
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/www/html
      name: 39821ef61c4568a75c2af78cd270bc65ee4da656d1d0dd4e89175f1f591243f0-pvc
  restartPolicy: Always
  volumes:
  - name: d88b83ee2a406925b6fd5efb630953d14c1cf0c11be69b9802fe0ed2d9cc3565-pvc
    persistentVolumeClaim:
      claimName: d88b83ee2a406925b6fd5efb630953d14c1cf0c11be69b9802fe0ed2d9cc3565
  - name: 39821ef61c4568a75c2af78cd270bc65ee4da656d1d0dd4e89175f1f591243f0-pvc
    persistentVolumeClaim:
      claimName: 39821ef61c4568a75c2af78cd270bc65ee4da656d1d0dd4e89175f1f591243f0
status: {}

